# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='foo.proto',
  package='foo',
  serialized_pb=_b('\n\tfoo.proto\x12\x03\x66oo\"\x13\n\x03\x42\x61r\x12\x0c\n\x04name\x18\x01 \x02(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BAR = _descriptor.Descriptor(
  name='Bar',
  full_name='foo.Bar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='foo.Bar.name', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=37,
)

DESCRIPTOR.message_types_by_name['Bar'] = _BAR

Bar = _reflection.GeneratedProtocolMessageType('Bar', (_message.Message,), dict(
  DESCRIPTOR = _BAR,
  __module__ = 'foo_pb2'
  # @@protoc_insertion_point(class_scope:foo.Bar)
  ))
_sym_db.RegisterMessage(Bar)


# @@protoc_insertion_point(module_scope)
