FROM python:2.7

ENV PYTHONUNBUFFERED 1

RUN apt-get update
RUN apt-get install -y vim
RUN pip install --upgrade pip

RUN apt-get install -y build-essential strace htop python-prctl libcap-dev
RUN pip install python-prctl

RUN pip install uwsgi

RUN mkdir /app
WORKDIR /app

ADD requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
RUN pip install Django==1.10
RUN pip install newrelic==2.54.0.41
