FROM python:2.7

ENV PYTHONUNBUFFERED 1

RUN apt-get update

RUN pip install uwsgi

RUN mkdir /code
WORKDIR /code

ADD requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt
RUN pip install Django==1.7.7
